### PR TITLE
make enscaped title and markdown text actually work.

### PR DESCRIPTION
**Pull request by revir**
1. title was escaped, but didn't unescape, so '&' in title would be displayed as '&amp;' on nodebb;

2. use `unescape` function does't really work, not even `decodeURIComponent`. Worse, `unescape` would make encoded unicode URL broken. I think the simplest way is using `element.innerText`.

### CODE REVIEW

**Comment by theunknownartisthour** [comment]
../post.markdown was escaped with {{}} in my last commit so that it wouldn't break the page w/ valid html that markdown sometimes uses. I did bring up the potential to use just a hidden span the last time. Which is funny, because that appears to be what you've done. 

But unescaping and escaped string definitely works, unfortunately you're not unescaping the now escaped markdown, which will definitely break something. Unless .innerText does some unescaping for you (it doesn't).

Didn't think to unescape the escaped title, but I was fairly certain someone else did that on purpose for NodeBB's sake.

**Comment by revir** [comment]
the `unescape` function is deprecated, it can't decode encoded html, it also would break decoded unicode text. See:  
1. https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/unescape
2. http://stackoverflow.com/questions/3700326/decode-amp-back-to-in-javascript

innerText does auto unescape, but not work for script tag, i don't know why. but works for span.

Are you sure you can unescape encoded html like '&amp' ?

**Comment by theunknownartisthour** [comment]
Unescape seems to be fine, doesn't touch the html: I used handlebar's escape function which is the same as {{}} to show what happens.

http://jsfiddle.net/bT7xV/41/

**Comment by revir** [comment]
`Unescape` doesn't really unescape anything, I test it on my website, which is based on NodeBB v1.3.0

This line: 

    var markdown = unescape(document.getElementById('nbb-markdown').innerHTML);

`markdown` is still escaped, after publish to nodebb, nodebb's parser would automatically unescape it.
So you can simply remove `unescape`.

    var markdown = document.getElementById('nbb-markdown').innerHTML;

It works all the same.

**Comment by revir** [comment]
In the jsfiddle, seems Ember.View has already do the unescape thing, not related to `unescape`, works with or without unescape.

**Comment by revir** [comment]
Hi, @theunknownartisthour, would you mind to take a look at: https://github.com/revir/nodebb-plugin-blog-comments2

I have added a bunch of new features to it, but it has break changes to your plugin, I added an `blogger` variable to distinguish posts from different blogs. Other features are below:

* Support multiple blogs, use `articleID` and `blogger` to distinguish posts from different blogs, so this is kinda break change to the original nodebb-plugin-blog-comments.
* Simple script for ghost, hugo, pelican etc, just add a `<script>` node at any place of the page, will support more blog platforms later.
* Use `siteTitle` instead of NodeBB in the `comments.tpl`.
* Fixed some bugs, like escaped title and content problems, profile image display, etc.

Would you like a PR?

**Comment by theunknownartisthour** [comment]
@psychobunny is really the person you should get to take a look at it. Makes sense to make different sites distinguishable, I think.

**Comment by revir** [comment]
Oh, that's right. I thought you are in charge.
This plugin works fine on NodeBB's current blog. My branch would break their current data, as well as others who are using this plugin. but also has some new features. I am not sure if I should keep it diverged or merge it in.
@psychobunny how do you think?

------------

@theunknownartisthour how about the unescape problem above? don't you think unescape is not working at all?

**Comment by psychobunny** [comment]
Apologies for missing this earlier

Happy to take a PR, I'm excited for the support for multiple blog platforms

**Comment by revir** [comment]
@psychobunny 
Merging the org branch should be safe, it just fixed the escaped title and markdown content.

But the master branch has a lot of differences, I add another variable `blogger` to distinguish blogs, see:

```javascript
Comments.getTopicIDByCommentID = function(commentID, blogger, callback) {
		db.getObjectField('blog-comments:'+blogger, commentID, function(err, tid) {
			callback(err, tid);
		});
	};
```

This might be a break change, be careful.

**Comment by psychobunny** [comment]
Yup, I saw that, it will break our current blog if I merged as-is :)

**Comment by revir** [comment]
So, do you think we should make it compatible or just leave it as a stand-alone plugin?

**Comment by psychobunny** [comment]
Up to you :)

**Comment by psychobunny** [comment]
Only one year later, but thank you!

**Pull request merged**
